spring.application.name=PRODUCT_SERVICE

spring.datasource.url=jdbc:mysql://localhost:3306/productservice
spring.datasource.username=root
spring.datasource.password=Hhpdh@4567$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=000
spring.mail.username=xyz@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.signature=jbwqjdndknwkdmowdmn12e9hdjnawldm3noendnmdpssm12p3kem;klsmoifn

